sudo: required

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-integration.txt
  - pip install -r requirements-unit.txt

before_script:
  - export SQLALCHEMY_DATABASE_URI='sqlite:///web.db'
  - python3 -m flask run > /dev/null &
  - while ! sudo lsof -Pi :5000 -sTCP:LISTEN -t; do sleep 1; done

script:
  - pytest unit_test
  - pytest integration_test
